cc_binary(
    name = "test_string",
    srcs = ['test_string.cpp',
    ],
    deps = ['//struct:redis_struct',
    ],
)

cc_binary(
    name = "test_list",
    srcs = ['test_list.cpp',
    ],
    deps = ['//struct:redis_struct',
    ],
)

cc_binary(
    name = "test_object",
    srcs = ['test_object.cpp',
    ],
    deps = ['//redis:redis_object',
    ],
)
cc_binary(
    name = "test_shared_ptr",
    srcs = ['test_shared_ptr.cpp',
    ],
)